// <auto-generated>
//     Generated from the CANONICAL Picto/src/shared/styles/tokens.css
//     by `Crystarium.Capture --generate-tokens`
//     (tools/ui-conformance/generate-tokens.ps1). Do not hand-edit.
//     `--verify-tokens` regenerates and fails on any diff or hash drift.
// </auto-generated>
using System.Numerics;

namespace Poser.UI;

/// <summary>
/// Committed generated projection of the Picto color tokens Crystarium
/// consumes, resolved per supported theme cascade. tokens.css is the
/// canonical source; production consumes this committed output and never
/// needs the Picto checkout or a generator run.
/// </summary>
internal static class PictoTokens
{
    /// <summary>SHA-256 of the LF-normalized canonical tokens.css.</summary>
    internal const string SourceHash = "37518f5c861e68a298e1c3757c34ef447827803b1e0eefabfc38b8f970c0ad8c";

    internal static class Dark
    {
        internal static readonly Vector4 BgApp = new(24f / 255f, 25f / 255f, 27f / 255f, 1f); // --color-bg-app
        internal static readonly Vector4 Surface1 = new(36f / 255f, 37f / 255f, 40f / 255f, 1f); // --color-surface-1
        internal static readonly Vector4 Surface2 = new(42f / 255f, 42f / 255f, 46f / 255f, 1f); // --color-surface-2
        internal static readonly Vector4 SurfaceHover = new(248f / 255f, 249f / 255f, 251f / 255f, 0.05f); // --color-surface-hover
        internal static readonly Vector4 SurfaceActive = new(248f / 255f, 249f / 255f, 251f / 255f, 0.1f); // --color-surface-active
        internal static readonly Vector4 TextPrimary = new(1f, 1f, 1f, 1f); // --color-text-primary
        internal static readonly Vector4 TextSecondary = new(1f, 1f, 1f, 0.72f); // --color-text-secondary
        internal static readonly Vector4 TextTertiary = new(1f, 1f, 1f, 0.5f); // --color-text-tertiary
        internal static readonly Vector4 BorderPrimary = new(1f, 1f, 1f, 0.14f); // --color-border-primary
        internal static readonly Vector4 BorderSecondary = new(1f, 1f, 1f, 0.08f); // --color-border-secondary
        internal static readonly Vector4 Primary = new(50f / 255f, 151f / 255f, 1f, 1f); // --color-primary
        internal static readonly Vector4 Primary10 = new(50f / 255f, 151f / 255f, 1f, 0.1f); // --color-primary-10
        internal static readonly Vector4 Primary30 = new(50f / 255f, 151f / 255f, 1f, 0.3f); // --color-primary-30
        internal static readonly Vector4 Primary50 = new(50f / 255f, 151f / 255f, 1f, 0.5f); // --color-primary-50
        internal static readonly Vector4 Primary60 = new(50f / 255f, 151f / 255f, 1f, 0.6f); // --color-primary-60
        internal static readonly Vector4 HoverOverlay = new(1f, 1f, 1f, 0.08f); // --color-hover-overlay
        internal static readonly Vector4 ActiveOverlay = new(1f, 1f, 1f, 0.14f); // --color-active-overlay
        internal static readonly Vector4 SubtleOverlay = new(1f, 1f, 1f, 0.1f); // --color-subtle-overlay
        internal static readonly Vector4 Black10 = new(0f, 0f, 0f, 0.1f); // --color-black-10
        internal static readonly Vector4 Black20 = new(0f, 0f, 0f, 0.2f); // --color-black-20
        internal static readonly Vector4 Negative = new(1f, 71f / 255f, 87f / 255f, 1f); // --color-negative
        internal static readonly Vector4 GlassBg = new(36f / 255f, 37f / 255f, 40f / 255f, 0.92f); // --glass-bg
        internal static readonly Vector4 GlassBorderTop = new(1f, 1f, 1f, 0.25f); // --glass-border-top
        internal static readonly Vector4 GlassBorderSide = new(1f, 1f, 1f, 0.12f); // --glass-border-side
        internal static readonly Vector4 GlassBorderBottom = new(0f, 0f, 0f, 0.2f); // --glass-border-bottom
    }

    internal static class Blue
    {
        internal static readonly Vector4 BgApp = new(15f / 255f, 23f / 255f, 50f / 255f, 1f); // --color-bg-app
        internal static readonly Vector4 Surface1 = new(23f / 255f, 31f / 255f, 58f / 255f, 1f); // --color-surface-1
        internal static readonly Vector4 Surface2 = new(28f / 255f, 36f / 255f, 65f / 255f, 1f); // --color-surface-2
    }

    internal static class Purple
    {
        internal static readonly Vector4 BgApp = new(30f / 255f, 21f / 255f, 38f / 255f, 1f); // --color-bg-app
        internal static readonly Vector4 Surface1 = new(38f / 255f, 29f / 255f, 46f / 255f, 1f); // --color-surface-1
        internal static readonly Vector4 Surface2 = new(43f / 255f, 34f / 255f, 53f / 255f, 1f); // --color-surface-2
    }

    internal static class Gray
    {
        internal static readonly Vector4 BgApp = new(50f / 255f, 50f / 255f, 54f / 255f, 1f); // --color-bg-app
        internal static readonly Vector4 Surface1 = new(58f / 255f, 58f / 255f, 62f / 255f, 1f); // --color-surface-1
        internal static readonly Vector4 Surface2 = new(63f / 255f, 63f / 255f, 69f / 255f, 1f); // --color-surface-2
    }

    internal static class Light
    {
        internal static readonly Vector4 BgApp = new(245f / 255f, 245f / 255f, 245f / 255f, 1f); // --color-bg-app
        internal static readonly Vector4 Surface1 = new(240f / 255f, 240f / 255f, 240f / 255f, 1f); // --color-surface-1
        internal static readonly Vector4 Surface2 = new(235f / 255f, 237f / 255f, 239f / 255f, 1f); // --color-surface-2
        internal static readonly Vector4 SurfaceHover = new(44f / 255f, 47f / 255f, 50f / 255f, 0.05f); // --color-surface-hover
        internal static readonly Vector4 SurfaceActive = new(44f / 255f, 47f / 255f, 50f / 255f, 0.1f); // --color-surface-active
        internal static readonly Vector4 TextPrimary = new(0f, 0f, 0f, 1f); // --color-text-primary
        internal static readonly Vector4 TextSecondary = new(0f, 0f, 0f, 0.72f); // --color-text-secondary
        internal static readonly Vector4 TextTertiary = new(0f, 0f, 0f, 0.5f); // --color-text-tertiary
        internal static readonly Vector4 BorderPrimary = new(0f, 0f, 0f, 0.12f); // --color-border-primary
        internal static readonly Vector4 BorderSecondary = new(0f, 0f, 0f, 0.06f); // --color-border-secondary
        internal static readonly Vector4 Primary = new(37f / 255f, 99f / 255f, 235f / 255f, 1f); // --color-primary
        internal static readonly Vector4 Primary10 = new(37f / 255f, 99f / 255f, 235f / 255f, 0.1f); // --color-primary-10
        internal static readonly Vector4 Primary30 = new(37f / 255f, 99f / 255f, 235f / 255f, 0.3f); // --color-primary-30
        internal static readonly Vector4 Primary50 = new(37f / 255f, 99f / 255f, 235f / 255f, 0.5f); // --color-primary-50
        internal static readonly Vector4 Primary60 = new(37f / 255f, 99f / 255f, 235f / 255f, 0.6f); // --color-primary-60
        internal static readonly Vector4 HoverOverlay = new(0f, 0f, 0f, 0.06f); // --color-hover-overlay
        internal static readonly Vector4 ActiveOverlay = new(0f, 0f, 0f, 0.1f); // --color-active-overlay
        internal static readonly Vector4 SubtleOverlay = new(0f, 0f, 0f, 0.08f); // --color-subtle-overlay
        internal static readonly Vector4 Black10 = new(0f, 0f, 0f, 0.1f); // --color-black-10
        internal static readonly Vector4 Black20 = new(0f, 0f, 0f, 0.2f); // --color-black-20
    }

    internal static class LightGray
    {
        internal static readonly Vector4 BgApp = new(200f / 255f, 202f / 255f, 205f / 255f, 1f); // --color-bg-app
        internal static readonly Vector4 Surface1 = new(208f / 255f, 210f / 255f, 213f / 255f, 1f); // --color-surface-1
        internal static readonly Vector4 Surface2 = new(194f / 255f, 196f / 255f, 199f / 255f, 1f); // --color-surface-2
        internal static readonly Vector4 BorderPrimary = new(171f / 255f, 173f / 255f, 175f / 255f, 1f); // --color-border-primary
        internal static readonly Vector4 BorderSecondary = new(0f, 0f, 0f, 0.08f); // --color-border-secondary
    }
}
