"""Generates the icon reference fixtures from the shipped source registry.

Reads Poser.UI/Icons/PoserIconSources.cs (wins) and TablerSvgSources.cs —
the same precedence Tabler.Get uses — and writes:

- icon-fixtures.generated.js: generated icon variants as inline SVGs on
  the exact geometry the corresponding candidate fixtures use. Loaded by
  picto-reference.html; variant keys keep the six-space indent the
  capture catalog cross-check scans for.
- icon-names.generated.txt: the ordinal-sorted name list, one per line.
  run.ps1 asserts it equals the candidate's `--icons` output, so the
  reference can never silently drift from Tabler.ShippedNames.

Deterministic: identical inputs produce identical bytes.
"""

import io
import math
import os
import re

TOOL_ROOT = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(os.path.dirname(TOOL_ROOT))

COLS = 8
STATE_ICONS = ["settings", "eye", "trash", "chevron-down"]
ICON_BUTTON_GLYPHS = [
    "plus",
    "x",
    "chevron-right",
    "chevron-down",
    "arrow-back-up",
    "folder",
    "settings",
]


def parse_sources(path):
    text = io.open(path, encoding="utf-8-sig").read()
    out = {}
    for match in re.finditer(
            r'\["([a-z0-9-]+)"\]\s*=\s*@"(.*?)"(?:,|\s*\n)', text, re.S):
        out[match.group(1)] = match.group(2).replace('""', '"').strip()
    return out


def svg_at(sources, name, x, y, size, stroke=None, extra_style=""):
    xml = re.sub(r"\s+", " ", sources[name]).replace("> <", "><")
    style = (f"{extra_style}position:absolute;left:{x}px;top:{y}px;"
             f"width:{size}px;height:{size}px")
    xml = xml.replace("<svg ", f'<svg style="{style}" ', 1)
    if stroke is not None:
        xml = xml.replace('stroke-width="2"', f'stroke-width="{stroke}"', 1)
    return xml


def grid_html(sources, names, size):
    pitch = size + 8
    parts = [
        svg_at(sources, name, (i % COLS) * pitch, (i // COLS) * pitch, size)
        for i, name in enumerate(names)
    ]
    return f'<div style="position:relative">{"".join(parts)}</div>'


def states_html(sources):
    pitch = 24
    rows = [
        (16, None, None, None),
        (16, None, 0.8, None),
        (16, None, 0.4, None),
        (16, "var(--color-primary)", None, None),
        (16, None, None, 1.5),
        (11, "var(--color-primary)", None, None),
    ]
    parts = []
    for r, (size, color, opacity, stroke) in enumerate(rows):
        for c, name in enumerate(STATE_ICONS):
            extra = ""
            if color:
                extra += f"color:{color};"
            if opacity is not None:
                extra += f"opacity:{opacity};"
            parts.append(svg_at(
                sources, name, c * pitch, r * pitch, size, stroke, extra))
    return f'<div style="position:relative">{"".join(parts)}</div>'


def icon_button_glyphs_html(sources):
    buttons = []
    for name in ICON_BUTTON_GLYPHS:
        xml = re.sub(r"\s+", " ", sources[name]).replace("> <", "><")
        xml = xml.replace('width="24"', 'width="16"', 1)
        xml = xml.replace('height="24"', 'height="16"', 1)
        xml = xml.replace('stroke-width="2"', 'stroke-width="1.5"', 1)
        buttons.append(
            f'<button class="iconBtn toggleBtn" aria-label="{name}">'
            f"{xml}</button>")
    return (
        '<div style="display:flex;gap:4px">'
        + "".join(buttons)
        + "</div>")


def esc(s):
    return s.replace("\\", "\\\\").replace("'", "\\'")


def main():
    tabler = parse_sources(os.path.join(
        REPO_ROOT, "Poser.UI", "Icons", "TablerSvgSources.cs"))
    custom = parse_sources(os.path.join(
        REPO_ROOT, "Poser.UI", "Icons", "PoserIconSources.cs"))
    sources = dict(tabler)
    sources.update(custom)
    names = sorted(sources.keys())
    rows = math.ceil(len(names) / COLS)

    js = (
        "// AUTO-GENERATED by generate-icon-fixtures.py from the shipped\n"
        "// Poser.UI/Icons sources - do not edit. Regenerated before every\n"
        "// reference capture.\n"
        "window.iconFixtures = {\n"
        "  names: [" + ", ".join(f"'{n}'" for n in names) + "],\n"
        "  variants: {\n"
        "      'icons-grid-16': {\n"
        "        css: 'app/globals.css',\n"
        f"        html: '{esc(grid_html(sources, names, 16))}',\n"
        "      },\n"
        "      'icons-grid-14': {\n"
        "        css: 'app/globals.css',\n"
        f"        html: '{esc(grid_html(sources, names, 14))}',\n"
        "      },\n"
        "      'icons-states': {\n"
        "        css: 'app/globals.css',\n"
        f"        html: '{esc(states_html(sources))}',\n"
        "      },\n"
        "      'icon-button-glyphs': {\n"
        "        css: ['shared/styles/iconButton.module.css',"
        " 'app/AppShell.module.css'],\n"
        f"        html: '{esc(icon_button_glyphs_html(sources))}',\n"
        "      },\n"
        "  },\n"
        "};\n"
    )
    with io.open(os.path.join(TOOL_ROOT, "icon-fixtures.generated.js"),
                 "w", encoding="utf-8", newline="\n") as f:
        f.write(js)
    with io.open(os.path.join(TOOL_ROOT, "icon-names.generated.txt"),
                 "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(names) + "\n")
    print(f"generated {len(names)} icons, {rows} grid rows")


if __name__ == "__main__":
    main()
