"""Component-sheet composition for the UI conformance workflow.

One layout implementation drives both sides:

- ``--layout`` computes the reference catalog page layout (all states of all
  components, absolutely positioned cells, origins snapped to multiples of 8
  so 1.25x/1.5x device scales land on integer pixels) and writes it for the
  reference page (``sheet-layout.generated.js``) and this script.
- ``--compose`` slices the single-process Edge catalog screenshot into cells,
  pairs each with its candidate capture (produced by the capture host's real
  pointer/keyboard/timing choreography), and composites ONE labeled sheet per
  component per side, plus a red diff sheet. Labels and chrome are stamped by
  the same code onto both sides, so they are byte-identical and diff-silent.
  It then rebuilds the comparison window (``artifacts/index.html``).

Numerical diagnostics (per-cell exact and significant mismatch, max channel
delta, provenance) are recorded in the combo manifest and shown in the
window only behind a collapsed details view. ``--verify-merge`` self-checks
the provenance-gated manifest merge without needing any capture.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
from PIL import Image, ImageDraw, ImageFont

TOOL_ROOT = Path(__file__).resolve().parent
CATALOG_PATH = TOOL_ROOT / "sheet-catalog.json"

# Page layout constants (CSS px). Origins snap to 8 so every supported
# device scale (1, 1.25, 1.5) maps them to integer physical pixels.
PAGE_PAD = 16
CELL_GAP = 16
CONTENT_WIDTH = 656

# A max-channel delta at or below this is invisible at 100% zoom (encoder
# rounding, subpixel AA); above it the difference is a real design mismatch.
SIGNIFICANT_DELTA = 8

# Sheet chrome (physical px, unscaled — it is diagnostics, not product).
SHEET_PAD = 16
SHEET_GAP = 16
TITLE_HEIGHT = 30
LABEL_HEIGHT = 18

WINDOW_BG = (16, 17, 20, 255)
CHROME_BG = (24, 25, 27, 255)
CHROME_TEXT = (255, 255, 255, 220)
LABEL_TEXT = (255, 255, 255, 140)
CELL_BORDER = (255, 255, 255, 24)


def snap8(value: int) -> int:
    return (value + 7) // 8 * 8


def load_catalog() -> list[dict]:
    return json.loads(CATALOG_PATH.read_text(encoding="utf-8"))["components"]


def page_layout(components: list[dict]) -> dict:
    """Absolute cell rectangles for the one-page reference catalog."""
    cells = []
    y = PAGE_PAD
    for component in components:
        x = PAGE_PAD
        row_height = 0
        for state in component["states"]:
            width, height = state["width"], state["height"]
            if x > PAGE_PAD and x + width > PAGE_PAD + CONTENT_WIDTH:
                x = PAGE_PAD
                y = snap8(y + row_height + CELL_GAP)
                row_height = 0
            cells.append({
                "name": state["name"],
                "component": component["name"],
                "x": x,
                "y": y,
                "w": width,
                "h": height,
            })
            x = snap8(x + width + CELL_GAP)
            row_height = max(row_height, height)
        y = snap8(y + row_height + 2 * CELL_GAP)
    return {
        "pageWidth": PAGE_PAD * 2 + CONTENT_WIDTH,
        "pageHeight": y + PAGE_PAD,
        "cells": cells,
    }


def write_layout() -> None:
    layout = page_layout(load_catalog())
    js = (
        "// Generated by sheets.py --layout from sheet-catalog.json.\n"
        "// Do not hand-edit.\n"
        f"window.sheetLayout = {json.dumps(layout, indent=1)};\n"
    )
    (TOOL_ROOT / "sheet-layout.generated.js").write_text(js, encoding="utf-8")
    print(f"layout: {layout['pageWidth']}x{layout['pageHeight']} CSS px, "
          f"{len(layout['cells'])} cells")


def label_font() -> ImageFont.ImageFont | ImageFont.FreeTypeFont:
    try:
        return ImageFont.truetype("C:/Windows/Fonts/segoeui.ttf", 11)
    except OSError:
        return ImageFont.load_default()


def sheet_layout(states: list[dict], scale: float) -> tuple[list[dict], int, int]:
    """Pack a component's cells (physical sizes) into one labeled sheet."""
    content = round(CONTENT_WIDTH * scale)
    slots = []
    x = SHEET_PAD
    y = SHEET_PAD + TITLE_HEIGHT
    row_height = 0
    for state in states:
        width, height = state["pw"], state["ph"] + LABEL_HEIGHT
        if x > SHEET_PAD and x + width > SHEET_PAD + content:
            x = SHEET_PAD
            y += row_height + SHEET_GAP
            row_height = 0
        slots.append({**state, "sx": x, "sy": y})
        x += width + SHEET_GAP
        row_height = max(row_height, height)
    sheet_w = SHEET_PAD * 2 + content
    sheet_h = y + row_height + SHEET_PAD
    return slots, sheet_w, sheet_h


def compose_sheet(title: str, slots: list[dict], size: tuple[int, int],
                  images: dict[str, Image.Image],
                  font) -> Image.Image:
    sheet = Image.new("RGBA", size, WINDOW_BG)
    draw = ImageDraw.Draw(sheet)
    draw.rectangle([0, 0, size[0] - 1, TITLE_HEIGHT - 1], fill=CHROME_BG)
    draw.text((SHEET_PAD, 8), title, fill=CHROME_TEXT, font=font)
    for slot in slots:
        cell = images[slot["name"]]
        sheet.paste(cell, (slot["sx"], slot["sy"]))
        draw.rectangle(
            [slot["sx"] - 1, slot["sy"] - 1,
             slot["sx"] + cell.width, slot["sy"] + cell.height],
            outline=CELL_BORDER,
        )
        draw.text(
            (slot["sx"], slot["sy"] + slot["ph"] + 3),
            slot["label"],
            fill=LABEL_TEXT,
            font=font,
        )
    return sheet


def diff_sheet(reference: Image.Image, candidate: Image.Image
               ) -> tuple[Image.Image, np.ndarray, np.ndarray, np.ndarray]:
    """Red heat map plus both mismatch channels and the raw per-pixel delta.

    The visible heat map paints the SIGNIFICANT channel only; the exact
    channel is a number in the diagnostics table, never a red pixel.
    """
    ref = np.asarray(reference, dtype=np.int16)[:, :, :3]
    cand = np.asarray(candidate, dtype=np.int16)[:, :, :3]
    delta = np.abs(ref - cand).max(axis=2)
    exact = delta > 0
    significant = delta > SIGNIFICANT_DELTA
    gray = np.clip(cand.mean(axis=2, keepdims=True) * 0.42, 0, 255)
    heat = np.repeat(gray, 3, axis=2).astype(np.uint8)
    strength = np.clip(delta.astype(np.float32) / 48.0, 0.25, 1.0)
    heat[significant, 0] = 255
    heat[significant, 1] = (
        heat[significant, 1] * (1 - strength[significant])).astype(np.uint8)
    heat[significant, 2] = (
        heat[significant, 2] * (1 - strength[significant])).astype(np.uint8)
    return (Image.fromarray(heat, "RGB").convert("RGBA"),
            exact, significant, delta)


def merge_components(prior_combo: dict | None, current_provenance: dict,
                     current_components: list[dict],
                     catalog_order: list[str]) -> list[dict]:
    """Components a rewritten combo manifest should contain.

    A partial run keeps the components it did not recompose ONLY when the
    prior manifest was produced from the identical reference/candidate
    identity; anything else is stale and is discarded rather than shown
    next to fresh sheets.
    """
    prior = list((prior_combo or {}).get("components", []))
    if not prior or (prior_combo or {}).get("provenance") != current_provenance:
        return list(current_components)
    order = {name: i for i, name in enumerate(catalog_order)}
    fresh = {c["name"] for c in current_components}
    kept = [c for c in prior if c["name"] not in fresh and c["name"] in order]
    merged = kept + [c for c in current_components if c["name"] in order]
    return sorted(merged, key=lambda c: order[c["name"]])


def compose(args: argparse.Namespace) -> None:
    components = load_catalog()
    if args.components:
        wanted = set(args.components.split(","))
        unknown = wanted - {c["name"] for c in components}
        if unknown:
            raise SystemExit(f"Unknown components: {', '.join(sorted(unknown))}")
        components = [c for c in components if c["name"] in wanted]

    artifacts = Path(args.artifacts)
    scale = float(args.scale)
    suffix = args.suffix
    layout = page_layout(load_catalog())
    catalog_png = artifacts / "picto" / f"catalog@{args.theme}@{suffix}.png"
    if not catalog_png.exists():
        raise SystemExit(f"Reference catalog capture missing: {catalog_png}")
    catalog_image = Image.open(catalog_png).convert("RGBA")
    cell_rects = {c["name"]: c for c in layout["cells"]}

    # A script error in the reference page renders a blank document, which
    # would silently diff every candidate against nothing. A real cell is
    # never perfectly uniform (text, borders); abort when too many are.
    catalog_array = np.asarray(catalog_image, dtype=np.int16)[:, :, :3]
    uniform = 0
    for rect in layout["cells"]:
        crop = catalog_array[rect["y"]:rect["y"] + rect["h"],
                             rect["x"]:rect["x"] + rect["w"]]
        if crop.size and (crop.max(axis=(0, 1)) == crop.min(axis=(0, 1))).all():
            uniform += 1
    if uniform * 4 > len(layout["cells"]):
        raise SystemExit(
            f"Reference catalog looks blank: {uniform} of "
            f"{len(layout['cells'])} cells are perfectly uniform - the "
            "reference page script likely failed (check picto-reference.html "
            "for JS errors; backticks inside template literals are fatal).")

    combo_dir = artifacts / "sheets" / f"{args.theme}@{suffix}"
    combo_dir.mkdir(parents=True, exist_ok=True)
    font = label_font()
    combo = {
        "theme": args.theme,
        "scale": scale,
        "suffix": suffix,
        "provenance": {
            "referenceManifestSha256": args.reference_hash,
            "candidateManifestSha256": args.candidate_hash,
            "candidateCommit": args.commit,
            "candidateDirty": args.dirty.lower() == "true",
        },
        "components": [],
    }

    for component in components:
        states = []
        ref_cells: dict[str, Image.Image] = {}
        cand_cells: dict[str, Image.Image] = {}
        for state in component["states"]:
            name = state["name"]
            cand_path = (artifacts / "crystarium"
                         / f"{name}@{args.theme}@{suffix}.png")
            if not cand_path.exists():
                raise SystemExit(f"Candidate capture missing: {cand_path}")
            cand = Image.open(cand_path).convert("RGBA")
            rect = cell_rects[name]
            left = round(rect["x"] * scale)
            top = round(rect["y"] * scale)
            ref = catalog_image.crop(
                (left, top, left + cand.width, top + cand.height))
            ref_cells[name] = ref
            cand_cells[name] = cand
            states.append({
                **state,
                "pw": cand.width,
                "ph": cand.height,
            })

        slots, sheet_w, sheet_h = sheet_layout(states, scale)
        title = component["title"]
        picto = compose_sheet(title, slots, (sheet_w, sheet_h), ref_cells, font)
        cryst = compose_sheet(title, slots, (sheet_w, sheet_h), cand_cells, font)
        diff, exact, significant, delta = diff_sheet(picto, cryst)

        # Component percentages are pixel-weighted: a one-pixel state must
        # not carry the same weight as a full-width row.
        cells_report = []
        total_pixels = 0
        total_exact = 0
        total_significant = 0
        for slot in slots:
            rows = slice(slot["sy"], slot["sy"] + slot["ph"])
            cols = slice(slot["sx"], slot["sx"] + slot["pw"])
            cell_exact = exact[rows, cols]
            cell_significant = significant[rows, cols]
            pixels = int(cell_exact.size)
            exact_count = int(cell_exact.sum())
            significant_count = int(cell_significant.sum())
            total_pixels += pixels
            total_exact += exact_count
            total_significant += significant_count
            cells_report.append({
                "name": slot["name"],
                "label": slot["label"],
                "exactPixels": exact_count,
                "exactPercent": round(exact_count / pixels * 100, 3),
                "significantPixels": significant_count,
                "significantPercent": round(
                    significant_count / pixels * 100, 3),
                "maxChannelDelta": int(delta[rows, cols].max()),
            })

        base = component["name"]
        picto.save(combo_dir / f"{base}.picto.png")
        cryst.save(combo_dir / f"{base}.crystarium.png")
        diff.save(combo_dir / f"{base}.diff.png")
        combo["components"].append({
            "name": base,
            "title": title,
            "exactPercent": round(total_exact / total_pixels * 100, 3),
            "significantPercent": round(
                total_significant / total_pixels * 100, 3),
            "cells": cells_report,
        })

    # Merge into any prior combo manifest so partial runs update their
    # components and leave the rest visible — but only while the prior
    # components describe the identical reference/candidate identity.
    combo_path = combo_dir / "combo.json"
    prior = (json.loads(combo_path.read_text(encoding="utf-8"))
             if combo_path.exists() else None)
    combo["components"] = merge_components(
        prior, combo["provenance"], combo["components"],
        [c["name"] for c in load_catalog()])
    combo_path.write_text(json.dumps(combo, indent=1), encoding="utf-8")
    write_window(artifacts, combo["provenance"])
    worst = max(
        (c for c in combo["components"]), key=lambda c: c["significantPercent"])
    print(f"sheets: {len(combo['components'])} components composed "
          f"({args.theme}@{suffix}); worst {worst['name']} "
          f"{worst['significantPercent']}%")


def write_window(artifacts: Path, provenance: dict) -> None:
    """Rebuild the window from the combos this run's identity produced.

    Combos left over from an older reference or candidate identity keep
    their files on disk but are hidden: the window never mixes identities.
    """
    combos = []
    for combo_path in sorted(artifacts.glob("sheets/*/combo.json")):
        combo = json.loads(combo_path.read_text(encoding="utf-8"))
        if combo.get("provenance") != provenance:
            continue
        combo["dir"] = f"sheets/{combo_path.parent.name}"
        combos.append(combo)
    if not combos:
        raise SystemExit(
            "No composed sheets match this run's provenance; nothing to show.")
    html = WINDOW_TEMPLATE.replace("__DATA__", json.dumps(combos))
    (artifacts / "index.html").write_text(html, encoding="utf-8")


def verify_merge() -> None:
    """Deterministic self-check of the provenance gate on the merge rule."""
    provenance = {
        "referenceManifestSha256": "ref-aaa",
        "candidateManifestSha256": "cand-aaa",
        "candidateCommit": "commit-aaa",
        "candidateDirty": False,
    }
    stale = {**provenance, "candidateManifestSha256": "cand-bbb"}
    order = ["alpha", "beta", "gamma"]

    def component(name: str, percent: float) -> dict:
        return {
            "name": name,
            "title": name.title(),
            "exactPercent": percent,
            "significantPercent": percent,
            "cells": [],
        }

    failures: list[str] = []

    def check(case: str, actual, expected) -> None:
        ok = actual == expected
        print(f"{'PASS' if ok else 'FAIL'} {case}")
        if not ok:
            failures.append(f"{case}: expected {expected!r}, got {actual!r}")

    prior = {"provenance": provenance,
             "components": [component("gamma", 3.0), component("alpha", 1.0)]}
    merged = merge_components(
        prior, provenance, [component("beta", 2.0)], order)
    check("matching provenance merges in catalog order",
          [c["name"] for c in merged], ["alpha", "beta", "gamma"])

    prior = {"provenance": stale,
             "components": [component("gamma", 3.0), component("alpha", 1.0)]}
    merged = merge_components(
        prior, provenance, [component("beta", 2.0)], order)
    check("mismatched provenance discards prior components",
          [c["name"] for c in merged], ["beta"])

    prior = {"provenance": provenance,
             "components": [component("alpha", 1.0), component("beta", 9.0)]}
    merged = merge_components(
        prior, provenance, [component("beta", 2.0)], order)
    check("superseded component is replaced, not duplicated",
          [(c["name"], c["significantPercent"]) for c in merged],
          [("alpha", 1.0), ("beta", 2.0)])

    if failures:
        for failure in failures:
            print(f"  {failure}")
        raise SystemExit(f"verify-merge: {len(failures)} case(s) failed.")
    print("verify-merge: 3 cases passed")


WINDOW_TEMPLATE = """<!doctype html>
<html><head><meta charset="utf-8"><title>Picto \u2194 Crystarium sheets</title>
<style>
:root{color-scheme:dark}
*{box-sizing:border-box}
body{margin:0;background:#101114;color:#fff;font:13px "Segoe UI",sans-serif;display:flex;height:100vh;overflow:hidden}
nav{width:230px;flex:none;border-right:1px solid #ffffff14;padding:10px;overflow-y:auto}
nav h1{font-size:14px;margin:4px 4px 10px}
nav select{width:100%;margin-bottom:10px;background:#1c1d20;color:#fff;border:1px solid #ffffff24;border-radius:6px;height:28px}
nav button{display:flex;justify-content:space-between;width:100%;text-align:left;background:none;border:0;color:#ffffffcc;padding:7px 8px;border-radius:6px;cursor:pointer;font:inherit}
nav button:hover{background:#ffffff10}
nav button.active{background:#3297ff1f;color:#fff}
nav .pct{color:#ffffff55;font-size:11px}
nav .pct.hot{color:#ff7a86}
main{flex:1;display:flex;flex-direction:column;min-width:0;overflow:hidden}
header{display:flex;gap:8px;align-items:center;padding:10px 14px;border-bottom:1px solid #ffffff14}
header .title{color:#ffffffcc}
header .zoom{margin-left:auto;display:flex;gap:4px}
header .zoom button{background:#1c1d20;border:1px solid #ffffff24;color:#ffffffcc;border-radius:5px;padding:4px 9px;cursor:pointer;font:inherit}
header .zoom button.active{border-color:#3297ff;color:#fff}
#columns{flex:1;display:grid;grid-template-columns:repeat(3,minmax(0,1fr));min-height:0}
#columns section{display:flex;flex-direction:column;min-width:0;min-height:0;border-right:1px solid #ffffff14}
#columns section:last-child{border-right:0}
#columns h2{font-size:11px;font-weight:400;letter-spacing:.06em;text-transform:uppercase;color:#ffffff77;margin:0;padding:7px 12px;border-bottom:1px solid #ffffff0d}
#columns .view{flex:1;overflow:auto;padding:12px}
#columns .canvas{position:relative}
#columns img{display:block;image-rendering:pixelated;transform-origin:top left}
details{border-top:1px solid #ffffff14;padding:8px 14px;color:#ffffff99;max-height:34vh;overflow:auto}
details table{border-collapse:collapse;margin-top:6px}
details td,details th{padding:2px 12px 2px 0;text-align:left;font-weight:400;color:#ffffffaa}
details .hot{color:#ff7a86}
code{color:#ffffff77}
</style></head><body>
<nav>
 <h1>Component sheets</h1>
 <select id="combo"></select>
 <div id="list"></div>
</nav>
<main>
 <header>
  <span class="title" id="title"></span>
  <div class="zoom" id="zoom"></div>
 </header>
 <div id="columns">
  <section><h2>Picto</h2><div class="view"><div class="canvas"><img id="img-picto"></div></div></section>
  <section><h2>Crystarium</h2><div class="view"><div class="canvas"><img id="img-crystarium"></div></div></section>
  <section><h2>Red diff</h2><div class="view"><div class="canvas"><img id="img-diff"></div></div></section>
 </div>
 <details id="diag"><summary>Diagnostics</summary><div id="diagBody"></div></details>
</main>
<script>
const DATA = __DATA__;
const KINDS = ["picto", "crystarium", "diff"];
const ZOOMS = [1, 2, 4];
let combo = 0, comp = null, zoom = 1;

const comboSel = document.getElementById("combo");
DATA.forEach((c, i) => {
  const option = document.createElement("option");
  option.value = i;
  option.textContent = c.theme + " @ " + c.scale + "\u00d7";
  comboSel.appendChild(option);
});
comboSel.addEventListener("change", () => { combo = +comboSel.value; buildList(); });

function buildList() {
  const list = document.getElementById("list");
  list.innerHTML = "";
  const components = DATA[combo].components;
  if (!components.some(c => c.name === comp)) comp = components[0].name;
  components.forEach(c => {
    const b = document.createElement("button");
    const pct = document.createElement("span");
    pct.className = "pct" + (c.significantPercent > 1 ? " hot" : "");
    pct.textContent = c.significantPercent.toFixed(2) + "%";
    b.textContent = c.title;
    b.appendChild(pct);
    if (c.name === comp) b.classList.add("active");
    b.addEventListener("click", () => { comp = c.name; buildList(); });
    list.appendChild(b);
  });
  render();
}

const zoomEl = document.getElementById("zoom");
ZOOMS.forEach(z => {
  const b = document.createElement("button");
  b.textContent = z + "\u00d7";
  if (z === zoom) b.classList.add("active");
  b.addEventListener("click", () => { zoom = z; refreshHeader(); render(); });
  zoomEl.appendChild(b);
});

// The three columns are one instrument: scrolling any of them mirrors the
// other two, so the same region of all three sheets stays under the eye.
const images = KINDS.map(k => document.getElementById("img-" + k));
const views = [...document.querySelectorAll("#columns .view")];
let syncing = false;
views.forEach(view => view.addEventListener("scroll", () => {
  if (syncing) return;
  syncing = true;
  views.forEach(other => {
    if (other === view) return;
    other.scrollLeft = view.scrollLeft;
    other.scrollTop = view.scrollTop;
  });
  // Mirrored scrolls fire their own events on the next frame; keep the
  // guard up until they have all landed.
  requestAnimationFrame(() => { syncing = false; });
}));
images.forEach(img => img.addEventListener("load", () => sizeCanvas(img)));

function sizeCanvas(img) {
  // transform:scale does not lay out, so the scroll box is sized here.
  const canvas = img.parentElement;
  canvas.style.width = (img.naturalWidth * zoom) + "px";
  canvas.style.height = (img.naturalHeight * zoom) + "px";
}

function refreshHeader() {
  [...zoomEl.children].forEach((b, i) => b.classList.toggle("active", ZOOMS[i] === zoom));
}

function render() {
  refreshHeader();
  const c = DATA[combo];
  const entry = c.components.find(x => x.name === comp);
  document.getElementById("title").textContent =
    entry.title + " \u00b7 " + entry.significantPercent.toFixed(2) + "% differing";
  images.forEach((img, i) => {
    const src = c.dir + "/" + comp + "." + KINDS[i] + ".png";
    if (img.getAttribute("src") !== src) img.setAttribute("src", src);
    img.style.transform = "scale(" + zoom + ")";
    if (img.complete && img.naturalWidth) sizeCanvas(img);
  });
  const p = c.provenance;
  const rows = entry.cells.map(cell =>
    `<tr><td>${cell.label}</td><td>${cell.exactPercent.toFixed(3)}%</td>` +
    `<td class="${cell.significantPercent > 1 ? "hot" : ""}">` +
    `${cell.significantPercent.toFixed(3)}%</td>` +
    `<td>${cell.maxChannelDelta}</td><td><code>${cell.name}</code></td></tr>`
  ).join("");
  document.getElementById("diagBody").innerHTML =
    `<table><tr><th>state</th><th>exact</th><th>significant</th>` +
    `<th>max \u0394</th><th>id</th></tr>${rows}</table>` +
    `<p>candidate <code>${p.candidateCommit.slice(0, 12)}${p.candidateDirty ? " + dirty" : ""}</code>` +
    ` \u00b7 reference manifest <code>${p.referenceManifestSha256.slice(0, 12)}</code>` +
    ` \u00b7 candidate manifest <code>${p.candidateManifestSha256.slice(0, 12)}</code></p>`;
}

buildList();
</script></body></html>
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--layout", action="store_true")
    parser.add_argument("--compose", action="store_true")
    parser.add_argument("--verify-merge", action="store_true")
    parser.add_argument("--theme", default="dark")
    parser.add_argument("--scale", default="1")
    parser.add_argument("--suffix", default="1")
    parser.add_argument("--components", default="")
    parser.add_argument("--artifacts", default=str(TOOL_ROOT / "artifacts"))
    parser.add_argument("--commit", default="")
    parser.add_argument("--dirty", default="false")
    parser.add_argument("--reference-hash", default="")
    parser.add_argument("--candidate-hash", default="")
    args = parser.parse_args()
    if args.verify_merge:
        verify_merge()
    if args.layout:
        write_layout()
    if args.compose:
        compose(args)
    if not args.layout and not args.compose and not args.verify_merge:
        parser.error(
            "nothing to do: pass --layout, --compose and/or --verify-merge")


if __name__ == "__main__":
    main()
