"""Component-sheet composition for the UI conformance workflow.

One layout implementation drives both sides:

- ``--layout`` computes the reference catalog page layout (all states of all
  components, absolutely positioned cells, origins snapped to multiples of 8
  so 1.25x/1.5x device scales land on integer pixels) and writes it for the
  reference page (``sheet-layout.generated.js``) and this script.
- ``--compose`` slices the single-process Edge catalog screenshot into cells,
  pairs each with its candidate capture (produced by the capture host's real
  pointer/keyboard/timing choreography), and composites ONE labeled sheet per
  component per side, plus a red diff sheet. Labels and chrome are stamped by
  the same code onto both sides, so they are byte-identical and diff-silent.
  It then rebuilds the comparison window (``artifacts/index.html``).

Numerical diagnostics (per-cell mismatch, provenance) are recorded in the
combo manifest and shown in the window only behind a collapsed details view.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
from PIL import Image, ImageDraw, ImageFont

TOOL_ROOT = Path(__file__).resolve().parent
CATALOG_PATH = TOOL_ROOT / "sheet-catalog.json"

# Page layout constants (CSS px). Origins snap to 8 so every supported
# device scale (1, 1.25, 1.5) maps them to integer physical pixels.
PAGE_PAD = 16
CELL_GAP = 16
CONTENT_WIDTH = 656

# Sheet chrome (physical px, unscaled — it is diagnostics, not product).
SHEET_PAD = 16
SHEET_GAP = 16
TITLE_HEIGHT = 30
LABEL_HEIGHT = 18

WINDOW_BG = (16, 17, 20, 255)
CHROME_BG = (24, 25, 27, 255)
CHROME_TEXT = (255, 255, 255, 220)
LABEL_TEXT = (255, 255, 255, 140)
CELL_BORDER = (255, 255, 255, 24)


def snap8(value: int) -> int:
    return (value + 7) // 8 * 8


def load_catalog() -> list[dict]:
    return json.loads(CATALOG_PATH.read_text(encoding="utf-8"))["components"]


def page_layout(components: list[dict]) -> dict:
    """Absolute cell rectangles for the one-page reference catalog."""
    cells = []
    y = PAGE_PAD
    for component in components:
        x = PAGE_PAD
        row_height = 0
        for state in component["states"]:
            width, height = state["width"], state["height"]
            if x > PAGE_PAD and x + width > PAGE_PAD + CONTENT_WIDTH:
                x = PAGE_PAD
                y = snap8(y + row_height + CELL_GAP)
                row_height = 0
            cells.append({
                "name": state["name"],
                "component": component["name"],
                "x": x,
                "y": y,
                "w": width,
                "h": height,
            })
            x = snap8(x + width + CELL_GAP)
            row_height = max(row_height, height)
        y = snap8(y + row_height + 2 * CELL_GAP)
    return {
        "pageWidth": PAGE_PAD * 2 + CONTENT_WIDTH,
        "pageHeight": y + PAGE_PAD,
        "cells": cells,
    }


def write_layout() -> None:
    layout = page_layout(load_catalog())
    js = (
        "// Generated by sheets.py --layout from sheet-catalog.json.\n"
        "// Do not hand-edit.\n"
        f"window.sheetLayout = {json.dumps(layout, indent=1)};\n"
    )
    (TOOL_ROOT / "sheet-layout.generated.js").write_text(js, encoding="utf-8")
    print(f"layout: {layout['pageWidth']}x{layout['pageHeight']} CSS px, "
          f"{len(layout['cells'])} cells")


def label_font() -> ImageFont.ImageFont | ImageFont.FreeTypeFont:
    try:
        return ImageFont.truetype("C:/Windows/Fonts/segoeui.ttf", 11)
    except OSError:
        return ImageFont.load_default()


def sheet_layout(states: list[dict], scale: float) -> tuple[list[dict], int, int]:
    """Pack a component's cells (physical sizes) into one labeled sheet."""
    content = round(CONTENT_WIDTH * scale)
    slots = []
    x = SHEET_PAD
    y = SHEET_PAD + TITLE_HEIGHT
    row_height = 0
    for state in states:
        width, height = state["pw"], state["ph"] + LABEL_HEIGHT
        if x > SHEET_PAD and x + width > SHEET_PAD + content:
            x = SHEET_PAD
            y += row_height + SHEET_GAP
            row_height = 0
        slots.append({**state, "sx": x, "sy": y})
        x += width + SHEET_GAP
        row_height = max(row_height, height)
    sheet_w = SHEET_PAD * 2 + content
    sheet_h = y + row_height + SHEET_PAD
    return slots, sheet_w, sheet_h


def compose_sheet(title: str, slots: list[dict], size: tuple[int, int],
                  images: dict[str, Image.Image],
                  font) -> Image.Image:
    sheet = Image.new("RGBA", size, WINDOW_BG)
    draw = ImageDraw.Draw(sheet)
    draw.rectangle([0, 0, size[0] - 1, TITLE_HEIGHT - 1], fill=CHROME_BG)
    draw.text((SHEET_PAD, 8), title, fill=CHROME_TEXT, font=font)
    for slot in slots:
        cell = images[slot["name"]]
        sheet.paste(cell, (slot["sx"], slot["sy"]))
        draw.rectangle(
            [slot["sx"] - 1, slot["sy"] - 1,
             slot["sx"] + cell.width, slot["sy"] + cell.height],
            outline=CELL_BORDER,
        )
        draw.text(
            (slot["sx"], slot["sy"] + slot["ph"] + 3),
            slot["label"],
            fill=LABEL_TEXT,
            font=font,
        )
    return sheet


def diff_sheet(reference: Image.Image, candidate: Image.Image
               ) -> tuple[Image.Image, np.ndarray]:
    ref = np.asarray(reference, dtype=np.int16)[:, :, :3]
    cand = np.asarray(candidate, dtype=np.int16)[:, :, :3]
    delta = np.abs(ref - cand).max(axis=2)
    exact = delta > 0
    gray = np.clip(cand.mean(axis=2, keepdims=True) * 0.42, 0, 255)
    heat = np.repeat(gray, 3, axis=2).astype(np.uint8)
    strength = np.clip(delta.astype(np.float32) / 48.0, 0.25, 1.0)
    heat[exact, 0] = 255
    heat[exact, 1] = (heat[exact, 1] * (1 - strength[exact])).astype(np.uint8)
    heat[exact, 2] = (heat[exact, 2] * (1 - strength[exact])).astype(np.uint8)
    return Image.fromarray(heat, "RGB").convert("RGBA"), exact


def compose(args: argparse.Namespace) -> None:
    components = load_catalog()
    if args.components:
        wanted = set(args.components.split(","))
        unknown = wanted - {c["name"] for c in components}
        if unknown:
            raise SystemExit(f"Unknown components: {', '.join(sorted(unknown))}")
        components = [c for c in components if c["name"] in wanted]

    artifacts = Path(args.artifacts)
    scale = float(args.scale)
    suffix = args.suffix
    layout = page_layout(load_catalog())
    catalog_png = artifacts / "picto" / f"catalog@{args.theme}@{suffix}.png"
    if not catalog_png.exists():
        raise SystemExit(f"Reference catalog capture missing: {catalog_png}")
    catalog_image = Image.open(catalog_png).convert("RGBA")
    cell_rects = {c["name"]: c for c in layout["cells"]}

    combo_dir = artifacts / "sheets" / f"{args.theme}@{suffix}"
    combo_dir.mkdir(parents=True, exist_ok=True)
    font = label_font()
    combo = {
        "theme": args.theme,
        "scale": scale,
        "suffix": suffix,
        "provenance": {
            "referenceManifestSha256": args.reference_hash,
            "candidateManifestSha256": args.candidate_hash,
            "candidateCommit": args.commit,
            "candidateDirty": args.dirty.lower() == "true",
        },
        "components": [],
    }

    for component in components:
        states = []
        ref_cells: dict[str, Image.Image] = {}
        cand_cells: dict[str, Image.Image] = {}
        for state in component["states"]:
            name = state["name"]
            cand_path = (artifacts / "crystarium"
                         / f"{name}@{args.theme}@{suffix}.png")
            if not cand_path.exists():
                raise SystemExit(f"Candidate capture missing: {cand_path}")
            cand = Image.open(cand_path).convert("RGBA")
            rect = cell_rects[name]
            left = round(rect["x"] * scale)
            top = round(rect["y"] * scale)
            ref = catalog_image.crop(
                (left, top, left + cand.width, top + cand.height))
            ref_cells[name] = ref
            cand_cells[name] = cand
            states.append({
                **state,
                "pw": cand.width,
                "ph": cand.height,
            })

        slots, sheet_w, sheet_h = sheet_layout(states, scale)
        title = component["title"]
        picto = compose_sheet(title, slots, (sheet_w, sheet_h), ref_cells, font)
        cryst = compose_sheet(title, slots, (sheet_w, sheet_h), cand_cells, font)
        diff, exact = diff_sheet(picto, cryst)

        cells_report = []
        for slot in slots:
            region = exact[
                slot["sy"]:slot["sy"] + slot["ph"],
                slot["sx"]:slot["sx"] + slot["pw"],
            ]
            cells_report.append({
                "name": slot["name"],
                "label": slot["label"],
                "mismatchPercent": round(float(region.mean() * 100), 3),
            })

        base = component["name"]
        picto.save(combo_dir / f"{base}.picto.png")
        cryst.save(combo_dir / f"{base}.crystarium.png")
        diff.save(combo_dir / f"{base}.diff.png")
        combo["components"].append({
            "name": base,
            "title": title,
            "mismatchPercent": round(
                float(np.mean([c["mismatchPercent"] for c in cells_report])), 3),
            "cells": cells_report,
        })

    # Merge into any prior combo manifest so partial runs update their
    # components and leave the rest visible.
    combo_path = combo_dir / "combo.json"
    if combo_path.exists() and args.components:
        prior = json.loads(combo_path.read_text(encoding="utf-8"))
        kept = [c for c in prior.get("components", [])
                if c["name"] not in {c["name"] for c in combo["components"]}]
        merged = kept + combo["components"]
        order = {c["name"]: i for i, c in enumerate(load_catalog())}
        combo["components"] = sorted(merged, key=lambda c: order[c["name"]])
    combo_path.write_text(json.dumps(combo, indent=1), encoding="utf-8")
    write_window(artifacts)
    worst = max(
        (c for c in combo["components"]), key=lambda c: c["mismatchPercent"])
    print(f"sheets: {len(combo['components'])} components composed "
          f"({args.theme}@{suffix}); worst {worst['name']} "
          f"{worst['mismatchPercent']}%")


def write_window(artifacts: Path) -> None:
    combos = []
    for combo_path in sorted(artifacts.glob("sheets/*/combo.json")):
        combo = json.loads(combo_path.read_text(encoding="utf-8"))
        combo["dir"] = f"sheets/{combo_path.parent.name}"
        combos.append(combo)
    if not combos:
        raise SystemExit("No composed sheets found.")
    html = WINDOW_TEMPLATE.replace("__DATA__", json.dumps(combos))
    (artifacts / "index.html").write_text(html, encoding="utf-8")


WINDOW_TEMPLATE = """<!doctype html>
<html><head><meta charset="utf-8"><title>Picto \u2194 Crystarium sheets</title>
<style>
:root{color-scheme:dark}
*{box-sizing:border-box}
body{margin:0;background:#101114;color:#fff;font:13px "Segoe UI",sans-serif;display:flex;height:100vh;overflow:hidden}
nav{width:230px;flex:none;border-right:1px solid #ffffff14;padding:10px;overflow-y:auto}
nav h1{font-size:14px;margin:4px 4px 10px}
nav select{width:100%;margin-bottom:10px;background:#1c1d20;color:#fff;border:1px solid #ffffff24;border-radius:6px;height:28px}
nav button{display:flex;justify-content:space-between;width:100%;text-align:left;background:none;border:0;color:#ffffffcc;padding:7px 8px;border-radius:6px;cursor:pointer;font:inherit}
nav button:hover{background:#ffffff10}
nav button.active{background:#3297ff1f;color:#fff}
nav .pct{color:#ffffff55;font-size:11px}
nav .pct.hot{color:#ff7a86}
main{flex:1;display:flex;flex-direction:column;min-width:0}
header{display:flex;gap:8px;align-items:center;padding:10px 14px;border-bottom:1px solid #ffffff14}
header .modes{display:flex;background:#1c1d20;border-radius:7px;padding:2px}
header .modes button{background:none;border:0;color:#ffffffaa;padding:5px 12px;border-radius:5px;cursor:pointer;font:inherit}
header .modes button.active{background:#3297ff33;color:#fff}
header .zoom{margin-left:auto;display:flex;gap:4px}
header .zoom button{background:#1c1d20;border:1px solid #ffffff24;color:#ffffffcc;border-radius:5px;padding:4px 9px;cursor:pointer;font:inherit}
header .zoom button.active{border-color:#3297ff;color:#fff}
header input[type=range]{width:160px}
#viewport{flex:1;overflow:auto;padding:16px}
#stage{position:relative;width:max-content}
#stage img{display:block;image-rendering:pixelated;transform-origin:top left}
#stage .top{position:absolute;left:0;top:0}
details{border-top:1px solid #ffffff14;padding:8px 14px;color:#ffffff99;max-height:34vh;overflow:auto}
details table{border-collapse:collapse;margin-top:6px}
details td,details th{padding:2px 12px 2px 0;text-align:left;font-weight:400;color:#ffffffaa}
details .hot{color:#ff7a86}
code{color:#ffffff77}
</style></head><body>
<nav>
 <h1>Component sheets</h1>
 <select id="combo"></select>
 <div id="list"></div>
</nav>
<main>
 <header>
  <div class="modes" id="modes"></div>
  <input type="range" id="mix" min="0" max="100" value="50" hidden>
  <div class="zoom" id="zoom"></div>
 </header>
 <div id="viewport"><div id="stage"></div></div>
 <details id="diag"><summary>Diagnostics</summary><div id="diagBody"></div></details>
</main>
<script>
const DATA = __DATA__;
const MODES = ["Picto", "Crystarium", "Diff", "Overlay"];
const ZOOMS = [1, 2, 4];
let combo = 0, comp = null, mode = 0, zoom = 1;

const comboSel = document.getElementById("combo");
DATA.forEach((c, i) => {
  const option = document.createElement("option");
  option.value = i;
  option.textContent = c.theme + " @ " + c.scale + "\u00d7";
  comboSel.appendChild(option);
});
comboSel.addEventListener("change", () => { combo = +comboSel.value; buildList(); });

function buildList() {
  const list = document.getElementById("list");
  list.innerHTML = "";
  const components = DATA[combo].components;
  if (!components.some(c => c.name === comp)) comp = components[0].name;
  components.forEach(c => {
    const b = document.createElement("button");
    const pct = document.createElement("span");
    pct.className = "pct" + (c.mismatchPercent > 1 ? " hot" : "");
    pct.textContent = c.mismatchPercent.toFixed(2) + "%";
    b.textContent = c.title;
    b.appendChild(pct);
    if (c.name === comp) b.classList.add("active");
    b.addEventListener("click", () => { comp = c.name; buildList(); });
    list.appendChild(b);
  });
  render();
}

const modesEl = document.getElementById("modes");
MODES.forEach((m, i) => {
  const b = document.createElement("button");
  b.textContent = m;
  if (i === mode) b.classList.add("active");
  b.addEventListener("click", () => { mode = i; refreshHeader(); render(); });
  modesEl.appendChild(b);
});
const zoomEl = document.getElementById("zoom");
ZOOMS.forEach(z => {
  const b = document.createElement("button");
  b.textContent = z + "\u00d7";
  if (z === zoom) b.classList.add("active");
  b.addEventListener("click", () => { zoom = z; refreshHeader(); render(); });
  zoomEl.appendChild(b);
});
const mix = document.getElementById("mix");
mix.addEventListener("input", render);

function refreshHeader() {
  [...modesEl.children].forEach((b, i) => b.classList.toggle("active", i === mode));
  [...zoomEl.children].forEach((b, i) => b.classList.toggle("active", ZOOMS[i] === zoom));
  mix.hidden = mode !== 3;
}

function render() {
  refreshHeader();
  const c = DATA[combo];
  const entry = c.components.find(x => x.name === comp);
  const stage = document.getElementById("stage");
  const src = kind => c.dir + "/" + comp + "." + kind + ".png";
  const img = (kind, cls) =>
    `<img class="${cls || ""}" src="${src(kind)}" style="transform:scale(${zoom})">`;
  if (mode === 0) stage.innerHTML = img("picto");
  else if (mode === 1) stage.innerHTML = img("crystarium");
  else if (mode === 2) stage.innerHTML = img("diff");
  else stage.innerHTML = img("picto") +
    `<div class="top" style="opacity:${mix.value / 100}">${img("crystarium")}</div>`;
  const p = c.provenance;
  const rows = entry.cells.map(cell =>
    `<tr><td>${cell.label}</td><td class="${cell.mismatchPercent > 1 ? "hot" : ""}">` +
    `${cell.mismatchPercent.toFixed(3)}%</td><td><code>${cell.name}</code></td></tr>`
  ).join("");
  document.getElementById("diagBody").innerHTML =
    `<table><tr><th>state</th><th>mismatch</th><th>id</th></tr>${rows}</table>` +
    `<p>candidate <code>${p.candidateCommit.slice(0, 12)}${p.candidateDirty ? " + dirty" : ""}</code>` +
    ` \u00b7 reference manifest <code>${p.referenceManifestSha256.slice(0, 12)}</code>` +
    ` \u00b7 candidate manifest <code>${p.candidateManifestSha256.slice(0, 12)}</code></p>`;
}

buildList();
</script></body></html>
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--layout", action="store_true")
    parser.add_argument("--compose", action="store_true")
    parser.add_argument("--theme", default="dark")
    parser.add_argument("--scale", default="1")
    parser.add_argument("--suffix", default="1")
    parser.add_argument("--components", default="")
    parser.add_argument("--artifacts", default=str(TOOL_ROOT / "artifacts"))
    parser.add_argument("--commit", default="")
    parser.add_argument("--dirty", default="false")
    parser.add_argument("--reference-hash", default="")
    parser.add_argument("--candidate-hash", default="")
    args = parser.parse_args()
    if args.layout:
        write_layout()
    if args.compose:
        compose(args)
    if not args.layout and not args.compose:
        parser.error("nothing to do: pass --layout and/or --compose")


if __name__ == "__main__":
    main()
