// GENERATED from Anamnesis Actor/Posing/Views/PoseMatrixView.xaml (modern
// variant) + Languages/en.json — the authoritative matrix layout the user's
// reference image shows. Regenerate with scratchpad tooling if Anamnesis
// changes; do NOT hand-edit rows.
namespace Poser.UI;

public static class AnamnesisMatrixTable
{
    public readonly record struct MatrixRow(string Section, string Label, (string Bone, string Pill)[] Pills);

    public static readonly MatrixRow[] Rows =
    {
        new("Head", "Head", new[] { ("Head", "") }),
        new("Head", "Jaw", new[] { ("j_f_ago", "1"), ("j_f_dago", "2") }),
        new("Head", "Ears", new[] { ("EarLeft", "L"), ("EarRight", "R") }),
        new("Head", "Cheeks", new[] { ("j_f_hoho_l", "L1"), ("j_f_shoho_l", "L2"), ("j_f_hoho_r", "R1"), ("j_f_shoho_r", "R2") }),
        new("Head", "Cheekbones", new[] { ("j_f_dmemoto_l", "L"), ("j_f_dmemoto_r", "R") }),
        new("Head", "Cheekbone Sides", new[] { ("j_f_dhoho_l", "L"), ("j_f_dhoho_r", "R") }),
        new("Head", "Nose", new[] { ("j_f_uhana", "C"), ("j_f_hana_l", "L"), ("j_f_hana_r", "R") }),
        new("Head", "Nose Bridge", new[] { ("j_f_dmiken_l", "L1"), ("j_f_miken_02_l", "L2"), ("j_f_dmiken_r", "R1"), ("j_f_miken_02_r", "R2") }),
        new("Head", "Viera Ears", new[] { ("VieraEar01ALeft", "L1"), ("VieraEar01BLeft", "L2"), ("VieraEar01ARight", "R1"), ("VieraEar01BRight", "R2"), ("VieraEar02ALeft", "L1"), ("VieraEar02BLeft", "L2"), ("VieraEar02ARight", "R1"), ("VieraEar02BRight", "R2"), ("VieraEar03ALeft", "L1"), ("VieraEar03BLeft", "L2"), ("VieraEar03ARight", "R1"), ("VieraEar03BRight", "R2"), ("VieraEar04ALeft", "L1"), ("VieraEar04BLeft", "L2"), ("VieraEar04ARight", "R1"), ("VieraEar04BRight", "R2") }),
        new("Eye", "Eyes", new[] { ("j_f_eye_l", "L1"), ("j_f_eyepuru_l", "L2"), ("j_f_eye_r", "R2"), ("j_f_eyepuru_r", "R2") }),
        new("Eye", "Left Eyelids", new[] { ("j_f_mabup_01_l", "U"), ("j_f_mabdn_01_l", "L") }),
        new("Eye", "Right Eyelids", new[] { ("j_f_mabup_01_r", "U"), ("j_f_mabdn_01_r", "L") }),
        new("Eye", "Eyebrows", new[] { ("j_f_mmayu_l", "L1"), ("j_f_mayu_l", "L2"), ("j_f_mmayu_r", "R1"), ("j_f_mayu_r", "R2") }),
        new("Eye", "Left Eye Corner", new[] { ("j_f_mabup_03in_l", "U1"), ("j_f_mabup_02out_l", "U2"), ("j_f_mabdn_03in_l", "L1"), ("j_f_mabdn_02out_l", "L2") }),
        new("Eye", "Right Eye Corner", new[] { ("j_f_mabup_03in_r", "U1"), ("j_f_mabup_02out_r", "U2"), ("j_f_mabdn_03in_r", "L1"), ("j_f_mabdn_02out_r", "L2") }),
        new("Eye", "Eye Socket", new[] { ("j_f_mab_l", "L"), ("j_f_mab_r", "R") }),
        new("Eye", "Iris", new[] { ("j_f_irisprm_l", "L1"), ("j_f_eyeprm_01_l", "L2"), ("j_f_irisprm_r", "R1"), ("j_f_eyeprm_01_r", "R2") }),
        new("Mouth", "Teeth", new[] { ("j_f_hagukiup", "1"), ("j_f_hagukidn", "2") }),
        new("Mouth", "Tongue", new[] { ("j_f_bero_01", "1"), ("j_f_bero_02", "2"), ("j_f_bero_03", "3") }),
        new("Mouth", "Left Upper Lip", new[] { ("j_f_ulip_01_l", "1"), ("j_f_ulip_02_l", "2"), ("j_f_umlip_01_l", "3"), ("j_f_umlip_02_l", "4") }),
        new("Mouth", "Right Upper Lip", new[] { ("j_f_ulip_01_r", "1"), ("j_f_ulip_02_r", "2"), ("j_f_umlip_01_r", "3"), ("j_f_umlip_02_r", "4") }),
        new("Mouth", "Left Lip Corners", new[] { ("j_f_uslip_l", "L1"), ("j_f_dslip_l", "L2") }),
        new("Mouth", "Left Lower Lip", new[] { ("j_f_dlip_01_l", "1"), ("j_f_dlip_02_l", "2"), ("j_f_dmlip_01_l", "3"), ("j_f_dmlip_02_l", "4") }),
        new("Mouth", "Right Lower Lip", new[] { ("j_f_dlip_01_r", "1"), ("j_f_dlip_02_r", "2"), ("j_f_dmlip_01_r", "3"), ("j_f_dmlip_02_r", "4") }),
        new("Mouth", "Right Lip Corners", new[] { ("j_f_uslip_r", "R1"), ("j_f_dslip_r", "R2") }),
        new("Hair and Accessories", "Earrings", new[] { ("EarringALeft", "L1"), ("EarringBLeft", "L2"), ("EarringARight", "R1"), ("EarringBRight", "R2") }),
        new("Hair and Accessories", "Whiskers", new[] { ("HrothWhiskersLeft", "L"), ("HrothWhiskersRight", "R") }),
        new("Hair and Accessories", "General", new[] { ("HairFrontLeft", "L"), ("HairFrontRight", "R"), ("HairA", "1"), ("HairB", "2") }),
        new("Body", "Neck", new[] { ("Neck", "") }),
        new("Body", "Cervical", new[] { ("SpineC", "") }),
        new("Body", "Thoracic", new[] { ("SpineB", "") }),
        new("Body", "Lumbar", new[] { ("SpineA", "") }),
        new("Body", "Abdomen", new[] { ("Abdomen", "") }),
        new("Body", "Scabbards", new[] { ("ScabbardLeft", "L"), ("ScabbardRight", "R") }),
        new("Body", "Clavicles", new[] { ("ClavicleLeft", "L"), ("ClavicleRight", "R") }),
        new("Body", "Breasts", new[] { ("BreastLeft", "L"), ("BreastRight", "R") }),
        new("Body", "Pauldrons", new[] { ("PauldronLeft", "L"), ("PauldronRight", "R") }),
        new("Body", "Shields", new[] { ("ShieldLeft", "L"), ("ShieldRight", "R") }),
        new("Body", "Shoulders", new[] { ("ShoulderLeft", "L"), ("ShoulderRight", "R") }),
        new("Body", "Arms", new[] { ("ArmLeft", "L"), ("ArmRight", "R") }),
        new("Body", "Couters", new[] { ("CouterLeft", "L"), ("CouterRight", "R") }),
        new("Body", "Elbows", new[] { ("ElbowLeft", "L"), ("ElbowRight", "R") }),
        new("Body", "Forearms", new[] { ("ForearmLeft", "L"), ("ForearmRight", "R") }),
        new("Body", "Wrists", new[] { ("WristLeft", "L"), ("WristRight", "R") }),
        new("Body", "IVCS Breasts", new[] { ("iv_c_mune_l", "L"), ("iv_c_mune_r", "R") }),
        new("Body", "IVCS Biceps", new[] { ("iv_nitoukin_l", "L"), ("iv_nitoukin_r", "R") }),
        new("Left Hand", "Hands", new[] { ("HandLeft", "") }),
        new("Left Hand", "Weapons", new[] { ("WeaponLeft", "") }),
        new("Left Hand", "Thumb", new[] { ("ThumbALeft", "1"), ("ThumbBLeft", "2") }),
        new("Left Hand", "Index", new[] { ("IndexALeft", "1"), ("IndexBLeft", "2"), ("iv_hito_c_l", "3") }),
        new("Left Hand", "Middle", new[] { ("MiddleALeft", "1"), ("MiddleBLeft", "2"), ("iv_naka_c_l", "3") }),
        new("Left Hand", "Ring", new[] { ("RingALeft", "1"), ("RingBLeft", "2"), ("iv_kusu_c_l", "3") }),
        new("Left Hand", "Pinky", new[] { ("PinkyALeft", "1"), ("PinkyBLeft", "2"), ("iv_ko_c_l", "3") }),
        new("Right Hand", "Hands", new[] { ("HandRight", "") }),
        new("Right Hand", "Weapons", new[] { ("WeaponRight", "") }),
        new("Right Hand", "Thumb", new[] { ("ThumbARight", "1"), ("ThumbBRight", "2") }),
        new("Right Hand", "Index", new[] { ("IndexARight", "1"), ("IndexBRight", "2"), ("iv_hito_c_r", "3") }),
        new("Right Hand", "Middle", new[] { ("MiddleARight", "1"), ("MiddleBRight", "2"), ("iv_naka_c_r", "3") }),
        new("Right Hand", "Ring", new[] { ("RingARight", "1"), ("RingBRight", "2"), ("iv_kusu_c_r", "3") }),
        new("Right Hand", "Pinky", new[] { ("PinkyARight", "1"), ("PinkyBRight", "2"), ("iv_ko_c_r", "3") }),
        new("Legs", "Legs", new[] { ("LegLeft", "L"), ("LegRight", "R") }),
        new("Legs", "Poleyns", new[] { ("PoleynLeft", "L"), ("PoleynRight", "R") }),
        new("Legs", "Knees", new[] { ("KneeLeft", "L"), ("KneeRight", "R") }),
        new("Legs", "Calves", new[] { ("CalfLeft", "L"), ("CalfRight", "R") }),
        new("Legs", "Sheathes", new[] { ("SheatheLeft", "L"), ("SheatheRight", "R") }),
        new("Legs", "Holsters", new[] { ("HolsterLeft", "L"), ("HolsterRight", "R") }),
        new("Legs", "Waist", new[] { ("Waist", "") }),
        new("Legs", "Tail", new[] { ("TailA", "1"), ("TailB", "2"), ("TailC", "3"), ("TailD", "4"), ("TailE", "5") }),
        new("Left Foot", "Foot", new[] { ("FootLeft", "") }),
        new("Left Foot", "Toes", new[] { ("ToesLeft", "") }),
        new("Left Foot", "Big", new[] { ("iv_asi_oya_a_l", "1"), ("iv_asi_oya_b_l", "2") }),
        new("Left Foot", "Index", new[] { ("iv_asi_hito_a_l", "1"), ("iv_asi_hito_b_l", "2") }),
        new("Left Foot", "Middle", new[] { ("iv_asi_naka_a_l", "1"), ("iv_asi_naka_b_l", "2") }),
        new("Left Foot", "Fore", new[] { ("iv_asi_kusu_a_l", "1"), ("iv_asi_kusu_b_l", "2") }),
        new("Left Foot", "Pinky", new[] { ("iv_asi_ko_a_l", "1"), ("iv_asi_ko_b_l", "2") }),
        new("Right Foot", "Foot", new[] { ("FootRight", "") }),
        new("Right Foot", "Toes", new[] { ("ToesRight", "") }),
        new("Right Foot", "Big", new[] { ("iv_asi_oya_a_r", "1"), ("iv_asi_oya_b_r", "2") }),
        new("Right Foot", "Index", new[] { ("iv_asi_hito_a_r", "1"), ("iv_asi_hito_b_r", "2") }),
        new("Right Foot", "Middle", new[] { ("iv_asi_naka_a_r", "1"), ("iv_asi_naka_b_r", "2") }),
        new("Right Foot", "Fore", new[] { ("iv_asi_kusu_a_r", "1"), ("iv_asi_kusu_b_r", "2") }),
        new("Right Foot", "Pinky", new[] { ("iv_asi_ko_a_r", "1"), ("iv_asi_ko_b_r", "2") }),
        new("Clothes", "Front", new[] { ("ClothFrontALeft", "L1"), ("ClothFrontBLeft", "L2"), ("ClothFrontCLeft", "L3"), ("ClothFrontARight", "R1"), ("ClothFrontBRight", "R2"), ("ClothFrontCRight", "R3") }),
        new("Clothes", "Back", new[] { ("ClothBackALeft", "L1"), ("ClothBackBLeft", "L2"), ("ClothBackCLeft", "L3"), ("ClothBackARight", "R1"), ("ClothBackBRight", "R2"), ("ClothBackCRight", "R3") }),
        new("Clothes", "Sides", new[] { ("ClothSideALeft", "L1"), ("ClothSideBLeft", "L2"), ("ClothSideCLeft", "L3"), ("ClothSideARight", "R1"), ("ClothSideBRight", "R2"), ("ClothSideCRight", "R3") }),
        new("Genitals", "Penis", new[] { ("iv_ochinko_a", "1"), ("iv_ochinko_b", "2"), ("iv_ochinko_c", "3"), ("iv_ochinko_d", "4"), ("iv_ochinko_e", "5"), ("iv_ochinko_f", "6") }),
        new("Genitals", "Scrotum", new[] { ("iv_kougan_l", "L"), ("iv_kougan_r", "R") }),
        new("Genitals", "Vagina", new[] { ("iv_omanko", "") }),
        new("Genitals", "Clitoris", new[] { ("iv_kuritto", "") }),
        new("Genitals", "Labia", new[] { ("iv_inshin_l", "L"), ("iv_inshin_r", "R") }),
        new("Genitals", "Anus", new[] { ("iv_koumon", ""), ("iv_koumon_l", "L"), ("iv_koumon_r", "R") }),
        new("Genitals", "Buttocks", new[] { ("iv_shiri_l", "L"), ("iv_shiri_r", "R") }),
    };
}
