using System.Collections.Immutable;

namespace Poser.Application.Settings;

public sealed record ReleaseNotesEntry(Version Version, string Title, ImmutableArray<string> Highlights);

/// <summary>Bundled user-facing release history, newest first.</summary>
public static class ReleaseNotesHistory
{
    public static ImmutableArray<ReleaseNotesEntry> Entries { get; } =
    [
        new(new(0, 9, 16), "Pinned Inspectors and clearer controls",
        [
            "Keep an entity's Inspector beside its pinned Properties, with a separate collapse button and actor-root transforms.",
            "Keep pop-out Properties the same minimum width as the main panel and identify pinned windows with a filled pin.",
            "Hide pop-outs and section separators consistently while transforming.",
            "Use right-drag to turn the free camera without left-click interfering with selection.",
            "Center the camera on an actor without changing your zoom or view angle.",
            "Reach camera, light and scenery file actions directly from buttons instead of a More dropdown.",
            "Find pose import, export and library actions under Actor > General.",
            "Choose pose export destinations from a nested submenu without losing the parent menu.",
            "Enjoy continuous rounded-window shadows that stay neutral across colour themes.",
            "Spot the main Properties title and release headings more easily.",
            "See character colours and custom colours in wider rectangular swatches without rearranging their rows.",
            "Open release notes with their heading font ready instead of briefly reflowing after display.",
            "Known limitation: Deselect in a pinned group Inspector can clear an unrelated global selection; avoid that action for now.",
        ]),
        new(new(0, 9, 15), "Smarter Properties pop-out placement",
        [
            "Open new Properties pop-outs at the size of your last adjusted window, with a small offset from its position.",
            "Keep new pop-outs on-screen and reuse the expanded size even after collapsing or closing the previous window.",
        ]),
        new(new(0, 9, 14), "Pinned Properties and better body colliders",
        [
            "Pop out Properties into separate windows that stay pinned to their original actors, objects or groups.",
            "Edit the same target from multiple windows while keeping bone selection and actor state in sync.",
            "Keep sections, pickers and animation scrubbing independent between Properties windows.",
            "Move pinned groups without accidentally editing the current selection instead.",
            "Generate better-fitting body and tail colliders that account for the current pose and Customize+ scaling.",
            "Keep generated colliders lightweight and preserve their group placement and bone attachments through Undo/Redo.",
            "Read Settings and Properties labels at minimum window widths without word wrapping.",
            "Reduce routine debug-log noise.",
        ]),
        new(new(0, 9, 13), "Idle export and appearance controls",
        [
            "Export idle poses with rotated, unevenly scaled bones without the transform-conversion error.",
            "Find Jaw and Jaw Only directly under Head in the skeleton tree.",
            "Right-click equipment or facewear to remove it, and dye or custom-colour swatches to clear them.",
            "Keep appearance colours and face controls in stable rows while editing or resizing the panel.",
            "Enter custom-colour brightness values above 1 in the colour picker.",
            "See every missed update on upgrade and browse release history from Settings.",
        ]),
        new(new(0, 9, 12), "idle-pose export, bone presets and movable dialogs",
        [
            "Export your posed actor and baked expression as a Penumbra idle-pose mod.",
            "Choose the standing pose slot, mod name and target races, with experimental cross-race retargeting.",
            "Save and export the PMP in one flow, then import it into Penumbra.",
            "Find common controls first in consistent entity menus, without unnecessary one-item submenus.",
            "Toggle facial-detail bones separately from the Head preset.",
            "Choose which bone presets appear when you show the skeleton, and manage them in a tidier list.",
            "Move dialogs freely and keep using the game or other windows without a blocking backdrop.",
        ]),
        new(new(0, 9, 11), "parenting, faster colliders and character-file improvements",
        [
            "Attach actors, lights, objects and colliders to another entity or an actor bone.",
            "Generated body colliders follow the actor's bones and remain individually editable.",
            "Draw colliders much faster, including older mesh colliders attached to moving bones.",
            "Keep collider settings and parent attachments when duplicating them.",
            "Switch duplicated actors to another Penumbra collection, with Reset and Undo/Redo support.",
            "Preserve face poses, head placement and custom face-paint colours when duplicating actors.",
            "Import Lightless MCDFs and export your main actor with Customize+ data.",
            "Play modded animations on MCDF actors through their normal Penumbra collection.",
            "Restore scene poses and camera views without unexpected pose drift or view changes.",
            "Create free cameras from the current view and keep rotation gizmos aligned near screen edges.",
            "Manage borrowed world objects and lights through shared editing and history controls.",
            "See short, non-blocking release highlights the first time a new version loads.",
        ]),
        new(new(0, 9, 10), "scene restoration and transform controls",
        [
            "Restore actor models and collections before scene poses, including attached companion placement.",
            "Save evaluated IK poses without changing the live scene.",
            "Load legacy Anamnesis and CMTool poses alongside modern pose files.",
            "Adjust capsule radius, endcap spacing and uniform scale independently.",
            "Keep directional scaling local while retaining uniform scaling in World mode.",
            "Show actual inspector values while transforms are locked.",
            "Clear actor nicknames between GPose sessions.",
            "Restore collider group visibility through Undo/Redo.",
        ]),
        new(new(0, 9, 9), "actor body colliders and world-space posing",
        [
            "Create a frozen, individually editable group of body colliders from an actor's current pose.",
            "Add capsule and sphere spawners; fit separate spine, shoulder, neck, limb and joint shapes with overlapping caps.",
            "Respect loaded model weights and racial deformation; handle packed bone influences and exclude hair, tails and non-body geometry before capture validation.",
            "Render legacy captured meshes as outlines and cache collider geometry.",
            "Prevent independent collision-chain links from accumulating unwanted twist.",
            "Keep World bone gizmo axes aligned to the world, including attached minions.",
            "Add bounded GPose lifetime diagnostics to investigate re-entry crashes; this is not a crash fix.",
        ]),
        new(new(0, 9, 8), "furniture and collider-aware chain IK",
        [
            "Add furniture as a dedicated spawn/sidebar/library category with dye, lighting and night controls.",
            "Update expression controls and camera orbit around moved actors; expand detached inspector numeric fields.",
            "Add parent and child spans for FABRIK and Rope, with parent-first defaults and a 50-link limit.",
            "Add transformable plane, box, cylinder and cone IK colliders using Bepu, with chain collision width and independent visibility, collision and lock controls.",
            "Improve collision stability, solver cost, bone rotations and rounded collider rendering.",
            "Clamp authored IK target coordinates at chain reach and discard excess drag distance.",
            "Save collider groups to the library and offer saved groups in spawn categories.",
            "Decouple inspector selection updates from Properties visibility; fix detached Close and Settings navigation/state behavior.",
            "Add enabled-by-default protection against game mouse target changes in GPose.",
            "Refine the first-run confirmation to say \"know what you're getting into.\"",
        ]),
        new(new(0, 9, 7), "world lifecycle and persistent workspace",
        [
            "Unify world borrowing controls and edit borrowed lights in place, with release restoring the original.",
            "Wait for spawned scenery/VFX replacements to become ready and preserve ownership through cleanup failures.",
            "Import human Anamnesis character files, including palette, equipment, dyes and facewear.",
            "Restore authored actor appearance, integration state and manual bone transforms through lifecycle history.",
            "Preserve Customize Plus on plain actor copies and copies of copies.",
            "Remember section disclosure and detached window geometry; add a hidden-handles default.",
            "Use consistent numbered names across created entities, and correct area-light labels and spotlight outlines.",
            "Add file-picker search, compact toolbar and scene-entity IK targets; fix preview isolation and drag history.",
            "Correct multi-key camera movement and scene-load history restoration.",
        ]),
        new(new(0, 9, 6), "scene fixes and consistent controls",
        [
            "Correct VFX borrowing/release lifecycle while preserving the accepted movement behavior.",
            "Fix library source initialization and diagnostics, with source management in Settings.",
            "Add stable group position, rotation and scale controls, including saved group orientation.",
            "Improve appearance layout, complete indexed palettes, later hairstyle previews and custom colours.",
            "Add attached-actor selection and controls, reorganize Actor sections, and correct ornament names.",
            "Correct gizmo screen sizing, rotation-ring projection and handle-versus-bone picking; ring visibility transitions gradually.",
            "Spawn lights closer to the camera.",
            "Put supported saves and category-wide destruction under the three-dot More menu; require confirmation for Destroy all.",
            "Add branch/weapon-slot/group Tree controls, explicit actor-wide presets and pose commands, and correct clicked-target routing.",
            "Preserve unrelated selections on entity removal and dismiss stale library menus after list changes.",
            "Expose None/0 weather explicitly. Some off-list weather still resolves to None, an accepted native limitation.",
        ]),
        new(new(0, 9, 5), "Spawned collections and undo gestures",
        [
            "Spawned creatures use the player’s Penumbra collection instead of retaining their catalogue name.",
            "Each slider drag or typed edit creates its own undo step.",
        ]),
        new(new(0, 9, 4), "Appearance restoration, input and bone presets",
        [
            "Restore the original appearance when reverting edits, removing an actor or leaving GPose.",
            "Consume only bound shortcuts, leaving ordinary game keys available.",
            "Use built-in bone visibility presets with IVCS bones grouped by body region.",
            "Keep the UI visible while fonts warm and size dialogs to their content.",
        ]),
        new(new(0, 9, 3), "World editing, wardrobe and workspace",
        [
            "Find game actors, creatures, props, scenery, lights and effects in the spawn menu.",
            "Dye supported scenery, pause its animation and toggle its visibility.",
            "Borrow world objects and duplicate actors, groups or mixed selections.",
            "Nest groups and preserve their structure when saving and spawning.",
            "Pose longer chains with FABRIK and control owned animation playback and scrubbing.",
            "Undo property edits across the scene.",
            "Edit appearance, outfits and equipment through Glamourer.",
            "Search Settings and preview changes before saving.",
            "Use a consistent workspace menu and improved overlay selection.",
            "Control free-camera orbit and keyboard movement.",
            "Browse library files with multi-selection and grouped autosaves.",
            "Save an issue report locally from Settings.",
            "Fix scene-streaming, borrowed-object lifetime and pose-import failures.",
        ]),
        new(new(0, 9, 2), "Groups, workspace and input",
        [
            "Group mixed entity types and transform, save or restore them together.",
            "Reorder scene entities and use shared multi-selection context menus.",
            "Use a separate library window, compact spawn menu and floating toolbar.",
            "Use consistent camera and gizmo modifiers with configurable shortcuts.",
            "Prevent overlay clicks from reaching the game and improve per-frame performance.",
        ]),
        new(new(0, 9, 0), "First public beta",
        [
            "Pose actors with on-screen gizmos, body maps and precise bone controls.",
            "Save and load poses and scenes, with configurable autosaves.",
            "Spawn actors and scene objects or borrow objects from the world.",
            "Create lights and free cameras to compose your shot.",
            "Set expressions and gaze targets.",
            "Add dialogue, reference images and other overlays.",
            "Import and export MCDF appearance files and organize a pose library.",
            "Configure shortcuts, overlay styles and posing controls.",
        ]),
    ];
}
